os: linux
dist: trusty
language: android

android:
    components:
        - platform-tools
        - tools
        - android-28
        - build-tools-28.0.3
        - extra-android-support
        - extra-android-m2repository
script:
    - make test
